# Style is important for readability and organization.
# The basic style is organized as follows:
# * Environment variables
# * Virtual targets
# * Real targets

# Your turn!
# Add 2 environment variables named 'INGREDIENTS' and 'DRESSING'.
# Add a default virtual rule that depends 'salad'.
# Add a rule targeting 'salad' that depends on $INGREDIENTS and $DRESSING.
# Have the recipe concatenate the prerequisites together.
# Add a rule that targets $INGREDIENTS.
# Add a rule that targets $DRESSING.
# Remember to use $target and $prereq where appropriate.
# Remember to actually create the files of non-virtual rules.
# run 'mk' to see the results!



# Check your solution with the mksolution to see if your style is right.
# Onto the next exercise!
